const puppeteer = require('puppeteer');

const generateReport = async (req, res) => {
  try {
    const { projectId } = req.params;

    const Project = require('../models/Project');
    const Expense = require('../models/Expense');
    const Worker = require('../models/Worker');
    const Material = require('../models/Material');
    const Tool = require('../models/Tool');

    const project = await Project.findById(projectId);
    if (!project) {
      return res.status(404).json({ message: 'Project not found' });
    }

    // Fetch related data
    const expenses = await Expense.find({ project: projectId });
    const workers = await Worker.find({ project: projectId });
    const materials = await Material.find({ project: projectId });
    const tools = await Tool.find({ project: projectId });

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page = await browser.newPage();

    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        body { font-family: 'Inter', Arial, sans-serif; margin: 40px; color: #1E293B; line-height: 1.5; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #F59E0B; padding-bottom: 20px; }
        h1 { color: #F59E0B; font-size: 28px; margin: 0; }
        h2 { color: #1E293B; margin-top: 30px; border-bottom: 2px solid #ddd; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #1E293B; color: white; font-weight: 600; }
        .highlight { color: #F59E0B; font-weight: 700; }
        .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #666; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>AGAP Construction</h1>
        <h2>Professional Project Report</h2>
        <p style="margin-top: 10px; font-size: 18px;">${project.name}</p>
      </div>

      <h2>Project Information</h2>
      <p><strong>Budget:</strong> ₱${Number(project.budget || 0).toLocaleString()}</p>
      <p><strong>Progress:</strong> ${project.progress || 0}%</p>
      <p><strong>Status:</strong> ${project.status?.toUpperCase() || 'PENDING'}</p>
      <p><strong>Location:</strong> ${project.location || '—'}</p>

      <h2>Financial Summary</h2>
      <p><strong>Total Expenses:</strong> ₱${Number(project.totalExpenses || 0).toLocaleString()}</p>
      <p><strong>Remaining Budget:</strong> ₱${(Number(project.budget || 0) - Number(project.totalExpenses || 0)).toLocaleString()}</p>

      <h2>Recent Expenses</h2>
      <table>
        <tr><th>Description</th><th>Amount</th></tr>
        ${expenses.length ? expenses.slice(0, 8).map(e => `
          <tr><td>${e.description}</td><td>₱${Number(e.amount).toLocaleString()}</td></tr>
        `).join('') : '<tr><td colspan="2">No expenses recorded</td></tr>'}
      </table>

      <h2>Assigned Workers</h2>
      <table>
        <tr><th>Name</th><th>Position</th><th>Daily Salary</th></tr>
        ${workers.length ? workers.slice(0, 8).map(w => `
          <tr><td>${w.name}</td><td>${w.position}</td><td>₱${Number(w.dailySalary || 0).toLocaleString()}</td></tr>
        `).join('') : '<tr><td colspan="3">No workers assigned</td></tr>'}
      </table>

      <h2>Materials Used</h2>
      <table>
        <tr><th>Name</th><th>Quantity</th><th>Unit Price</th></tr>
        ${materials.length ? materials.slice(0, 6).map(m => `
          <tr><td>${m.name}</td><td>${m.quantity}</td><td>₱${Number(m.unitPrice || 0).toLocaleString()}</td></tr>
        `).join('') : '<tr><td colspan="3">No materials recorded</td></tr>'}
      </table>

      <div class="footer">
        Generated by AGAP Construction Management System • ${new Date().toLocaleDateString('en-PH')}
      </div>
    </body>
    </html>`;

    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: 30, bottom: 30, left: 30, right: 30 }
    });

    await browser.close();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${project.name.replace(/[^a-zA-Z0-9]/g, '_')}_report.pdf"`);
    res.send(pdfBuffer);

  } catch (error) {
    console.error('PDF Generation Error:', error);
    res.status(500).json({ message: 'Failed to generate PDF', error: error.message });
  }
};

module.exports = { generateReport };